### ISSUE TITLE
task: welcome screen

### ISSUE THREAD

**Issue by Nasfame** [DeCenter-AI/app.decenterai.com#126]
### Task description

- [ ]  https://www.figma.com/file/HWwY6JKy3bnnu1SfSeRL8d/DeCenter-AI?type=design&node-id=526-2488&mode=design&t=3yarDdI7IQCRmR1R-0
- [ ] https://www.figma.com/file/HWwY6JKy3bnnu1SfSeRL8d/DeCenter-AI?type=design&node-id=526-2488&mode=design&t=3yarDdI7IQCRmR1R-0
- [ ] allow uploading pictures, upload the picture with lighthouse sdk
- [ ] retrieve and update in userStore (zustand cache)

![Image](https://github.com/DeCenter-AI/app.decenterai.com/assets/24226219/eaa25ba7-d361-47c6-8989-8e60f9cd4979)

![Image](https://github.com/DeCenter-AI/app.decenterai.com/assets/24226219/7669dbd6-500c-420c-8a89-0c557423006c)

**Comment by utkarsh-1602** [comment]
using this package `npm i @lighthouse-web3/sdk`

**Comment by Nasfame** [comment]
@utkarsh-1602 u r expected to store with lighthouse sdk. we have the upload code in our codebase. Check the train new model flow. @techyNonso guide him.

**Comment by Nasfame** [comment]
@utkarsh-1602 make sure u r able to update rest of the details to cache 1st, and in the end figure out the lighthouse code.

**Comment by Nasfame** [comment]
@utkarsh-1602 kindly raise the PR asap, so that i can review the UI u created

**Comment by Nasfame** [comment]
@utkarsh-16 what's the update???
