### ISSUE TITLE
feat: integrate stores to modelTrain flow

### ISSUE THREAD

**Issue by Nasfame** [DeCenter-AI/app.decenterai.com#130]
### Task description

- [x] create modelStore, trainingRequest Store @techyNonso 
- [x] put the dummy data in `init` , so that we can verify the UI works alright @techyNonso 
- [x] create apis to add trainingRequest, models to DB (refer prisma/seed.ts). Refer src/app/api/prisma/**.ts @Sheriff-Oladimeji 
- [x] create the apis to createTrainingRequest, models. @Sheriff-Oladimeji 
- [ ] integrate the apis:  similar to userStore with init, sync @Sheriff-Oladimeji

**Comment by Nasfame** [comment]
Relates to #147
