### ISSUE TITLE
task: evaluate app.decenterai.com

### ISSUE THREAD

**Issue by Nasfame** [DeCenter-AI/app.decenterai.com#137]
### Task description

- [x] evaluate on the basis of the figma designs
- [x] mention the ui screens that needs to improve
- [x] mention the flows missing
- [x] create a separate "task" ticket: to make the fixes and assign it to me.
