### ISSUE TITLE
mvp: disable unfinished flows

### ISSUE THREAD

**Issue by Nasfame** [DeCenter-AI/app.decenterai.com#145]
### Task description

- [ ] comment the code for the below button [it shouldn't be visible] - mention this ticket after the code
- [ ] comment the [Security button](https://app.decenterai.com/dashboard/settings). mention this ticket 
- [ ] disable wallet comment: on overlay display "feature in development"
- [ ] Remove "to the top" from notification widget
- [ ] Comment: downloads, tasks (shouldn't be visible in UI)
- [ ] Comment the code: "Mark all as read" [don't show in UI] 
- [ ] COmment the code for: "Filter by Name, sort, grid icon" [don't show in UI]
- [ ] dashLayout.tsx: remove the search bar

![Image](https://github.com/DeCenter-AI/app.decenterai.com/assets/24226219/23f4e4b3-4a12-4b2d-9ca3-ee65848a1c08)

![Image](https://github.com/DeCenter-AI/app.decenterai.com/assets/24226219/167975a6-b7b3-4820-b30c-a56485a64d0a)

![Image](https://github.com/DeCenter-AI/app.decenterai.com/assets/24226219/6c999be8-dab4-4a89-9472-90c97b11e9f2)

![Image](https://github.com/DeCenter-AI/app.decenterai.com/assets/24226219/d8308c50-ffbe-47ae-aec5-92058a6a94d0)

![Image](https://github.com/DeCenter-AI/app.decenterai.com/assets/24226219/9fc9120a-eb41-44b5-a22f-74ce20f179f7)

![Image](https://github.com/DeCenter-AI/app.decenterai.com/assets/24226219/aa5e652a-194c-41a2-979a-9d8888ad9a80)

![Image](https://github.com/DeCenter-AI/app.decenterai.com/assets/24226219/d6ff7110-6289-421a-b632-1869093e637f)

![Image](https://github.com/DeCenter-AI/app.decenterai.com/assets/24226219/a3e5da12-8ed7-4628-be22-ce159a5c0e26)
