### ISSUE TITLE
meta/favicon: fixes, enhanced

### ISSUE THREAD

**Issue by Nasfame** [DeCenter-AI/app.decenterai.com#39]
https://realfavicongenerator.net/favicon_checker?protocol=http&site=app.decenterai.com 

- [x] - [ ] Couldn't generate: `android-chrome-512x512.png` with https://realfavicongenerator.net as the logo used was small. @VictorKaycee17 kindly share a bigger logo for favicon. 
- [x] Fix: Mac OS X El Capitan Safari @Codebox124 
- [x] Fix: iOS Safari @Codebox124 
- [x] Fix: Android Chrome  @Codebox124  after @VictorKaycee17 shares a larger input png. Use it to generate the favicons and see if it has `android-chrome-512x512.png`

**Comment by Nasfame** [comment]
@Codebox124 what's the update on this tick. Kindly tick the fixes that has been applied

**Comment by Nasfame** [comment]
@Codebox124 use this to generate favicon: https://drive.google.com/file/d/1lc9IqPgCQETJTpNEWU-Vgpwdj4IIFnHv/view?usp=share_link
